<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>远程安装客户端</AssemblyName>
    <RootNamespace>RemoteInstallCustomer</RootNamespace>
    <ApplicationIcon>..\res\icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <EmbeddedResource Include="payload.zip" LogicalName="payload.zip" Condition="Exists('payload.zip')" />
  </ItemGroup>
</Project>
